import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import type { NextPage } from 'next'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import Maps from '../components/Maps'

// import { Database } from '../utils/database.types'
// type Profiles = Database['public']['Tables']['profiles']['Row']

// [START maps_add_map]
// Initialize and add the map
function initMap(): void {
  // [START maps_add_map_instantiate_map]
  // The location of Uluru
  const uluru = { lat: -25.344, lng: 131.031 };
  // The map, centered at Uluru
  const map = new google.maps.Map(
    document.getElementById("map") as HTMLElement,
    {
      zoom: 4,
      center: uluru,
    }
  );
  // [END maps_add_map_instantiate_map]

  // [START maps_add_map_instantiate_marker]
  // The marker, positioned at Uluru
  const marker = new google.maps.Marker({
    position: uluru,
    map: map,
  });
  // [END maps_add_map_instantiate_marker]
}

declare global {
  interface Window {
    initMap: () => void;
  }
}
//window.initMap = initMap;

export default function Home({}) {
  const loc = ["37.4218", "-122.0840"];
  const url = "https://www.google.com/maps/embed/v1/place?key=AIzaSyDSUiAdbzRWOD8raCNMlH8x5fD14wtXT7s&q=" + loc[0] + "," + loc[1];
    //window.initMap = initMap;

  const session = useSession()
  const supabase = useSupabaseClient()
  //const session = useSession()
  //const supabase = useSupabaseClient()
  //const [profiles, setProfiles] = useState([])
  // const [name, setName] = useState<Profiles['name']>(null)
  // For user single user input
  //const [UUID, setUUID] = useState({ uid: "",name: ""})
  //const { uid, name } = profiles
  // useEffect(() => {
  //   fetchPosts()
  //    //console.log("Profile data: " + prof);
  // }, [])
    
  // async function fetchPosts() {
  //   try {

  //     let { data, error, status } = await supabase
  //     .from("profiles")
  //     .select(`*`);
  //     //setProfiles(data)
  //     if(data){
  //       setName(data);
  //       console.log("data is: ", data)
  //     }
  //     //return data
  //   }
  //   catch (error) {
  //     alert('Error loading data')
  //     console.log(error)
  //   }
  // }

  // async function insertProfile() {
  //   try {
  //     let { data } = await supabase
  //     .from('profiles')
  //     .insert([
  //       { state: 1, name: 'Jose', description: 'this is a description'}
  //     ])
  //     //setProfiles(data)
  //     console.log("data: ", data)
  //   }
  //   catch (error) {
  //     alert('Error loading data')
  //     console.log(error)
  //   }
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
        <div id="map"></div>

        <div> 
        {/* <button
        className="button primary block"
        onClick={() => fetchPosts()}
        >Click me</button> */}
        
        </div>
          {/* <!-- 
          The `defer` attribute causes the callback to execute after the full HTML
          document has been parsed. For non-blocking uses, avoiding race conditions,
          and consistent behavior across browsers, consider loading using Promises
          with https://www.npmjs.com/package/@googlemaps/js-api-loader.
          --> */}
          {/* <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSUiAdbzRWOD8raCNMlH8x5fD14wtXT7s&callback=initialize"
            defer
          ></script> */}

        </div>
         <iframe
          width="450"
          height="250"
          frameBorder="0"
          referrerPolicy="no-referrer-when-downgrade"
          // https://www.google.com/maps/embed/v1/place?key=AIzaSyDSUiAdbzRWOD8raCNMlH8x5fD14wtXT7s&&q=Eiffel+Tower,Paris+France
          src={url}
          allowFullScreen>
        </iframe>

        <div>
        {/* {!session ? (
        <div className="row">
          <div className="col-6">
            <h1 className="header">Supabase Auth + Storage</h1>
            <p className="">
              Experience our Auth and Storage through a simple profile management example. Create a
              user profile and upload an avatar image. Fast, simple, secure.
            </p>
          </div>
          <div className="col-6 auth-widget">
            <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />
          </div>
        </div>
      ) : ( */}
        <>
          <h3>Account</h3>
          <Maps/>
        </>
      {/* )} */}

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
